# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f59301dac3dbc000fd3ef38f1d160657"
name = "Discounts"
handle = "discounts-147"
application_url = "https://jpg-viral-purchased-treatment.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9757cb94.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://jpg-viral-purchased-treatment.trycloudflare.com/auth/callback",
  "https://jpg-viral-purchased-treatment.trycloudflare.com/auth/shopify/callback",
  "https://jpg-viral-purchased-treatment.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
